const selfCareActivities = [
  "Pour yourself a tea/coffee in your favourite mug/cup",
  "Do your hair differently today",
  "Indulge in a sweet treat",
  "Watch the sunrise",
  "Watch the sunset",
  "Walk barefoot – anywhere – for 5 mins",
  "Take a different way to the shops (or work/school/Uni/etc.)",
  "Lie in bed for a minute the moment you wake up and just observe the moment",
  "No social media 90 minutes before bed time",
  "Sketch/draw/doodle for 5 minutes",
  "Read 5 pages from a book on your reading list",
  "Check-in with yourself throughout the day to ensure that you don’t get overwhelmed",
  "Write a postcard to someone you haven’t contacted in awhile",
  "Journal",
  "Cook a meal whilst listening to your favorite music",
  "Dance your heart out to your favorite music",
  "Go for an early morning walk",
  "Go for a walk while the sun sets",
  "Connect with a friend or significant other through conversation even if it’s just for 5 minutes of your day",
  "Sit in your garden for 5 mins and just observe",
  "Enjoy a hot shower",
  "Do a mini-declutter",
  "Go to bed early",
  "Get up a few minutes earlier than usual and fill these minutes with some quiet contemplation",
  "Set aside some “worry time” (10 mins) where you allow yourself to focus on all your worries. Acknowledge them, then let it go",
  "Laugh: read or watch something funny",
  "Have a date with yourself",
  "Splurge on something small",
  "Treat yourself",
  "Stretch",
  "Give yourself a massage",
  "Take a photo of your day",
  "Window shop online or at the shops and create a wishlist",
  "Schedule in some me time and do whatever you want!",
  "Write down what you’re grateful for and post it somewhere you can be reminded of it daily",
  "Call someone just to say hello",
  "Turn off your phone today, or if you can’t for whatever reason, at least turn it off for an hour",
  "Sing in the shower, whilst hanging out the laundry, washing the dishes, etc. – just sing",
  "Cook/bake something and give it to a friend, family member, neighbor, etc",
  "Listen to a podcast that interests you",
  "Discover a new blog based on your interests, and leave a comment or email the blogger",
  "Write some positive thoughts on a post-it note and leave it at a bookstore, newsstand, coffee shop, etc",
  "Have a picnic in an unconventional place, like your living room or veranda, invite people you love to join you",
  "Make your favourite meal/snack and enjoy it uninterrupted and be in the moment (no media or work)",
  "Ask for help if you need it today",
  "People watch when you’re out today, but don’t judge, just observe",
  "Compliment yourself and mean it",
  "Look at the stars",
  "Take a nap",
  "Watch the clouds",
  "Read and enjoy a magazine",
  "Watch your favourite movie",
  "Only do ONE thing on your to-do list",
  "Do absolutely nothing for 15 mins",
  "Get dressed up for no reason",
  "Try a new healthy recipe for a snack or one of your main meals",
  "Daydream",
  "Indulge in a hobby",
  "Order dinner in or have someone else make it",
  "Buy yourself a bouquet of flowers or arrange/pick flowers from your garden",
  "Drink water",
  "Color-in some coloring-in pages"
]

export default selfCareActivities